/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocasRouteImport } from './routes/trocas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RastreioRouteImport } from './routes/rastreio'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as EnvioRouteImport } from './routes/envio'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ApiPublicClaimCouponRouteImport } from './routes/api/public/claim-coupon'

const TrocasRoute = TrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RastreioRoute = RastreioRouteImport.update({
  id: '/rastreio',
  path: '/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvioRoute = EnvioRouteImport.update({
  id: '/envio',
  path: '/envio',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaimCouponRoute = ApiPublicClaimCouponRouteImport.update({
  id: '/api/public/claim-coupon',
  path: '/api/public/claim-coupon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/envio': typeof EnvioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/claim-coupon': typeof ApiPublicClaimCouponRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/envio': typeof EnvioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/claim-coupon': typeof ApiPublicClaimCouponRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/envio': typeof EnvioRoute
  '/privacidade': typeof PrivacidadeRoute
  '/rastreio': typeof RastreioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/trocas': typeof TrocasRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/api/public/claim-coupon': typeof ApiPublicClaimCouponRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/envio'
    | '/privacidade'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas'
    | '/categoria/$slug'
    | '/product/$handle'
    | '/api/public/claim-coupon'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/envio'
    | '/privacidade'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas'
    | '/categoria/$slug'
    | '/product/$handle'
    | '/api/public/claim-coupon'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/envio'
    | '/privacidade'
    | '/rastreio'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/trocas'
    | '/categoria/$slug'
    | '/product/$handle'
    | '/api/public/claim-coupon'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EnvioRoute: typeof EnvioRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RastreioRoute: typeof RastreioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  TrocasRoute: typeof TrocasRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  ApiPublicClaimCouponRoute: typeof ApiPublicClaimCouponRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocas': {
      id: '/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof TrocasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rastreio': {
      id: '/rastreio'
      path: '/rastreio'
      fullPath: '/rastreio'
      preLoaderRoute: typeof RastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envio': {
      id: '/envio'
      path: '/envio'
      fullPath: '/envio'
      preLoaderRoute: typeof EnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/claim-coupon': {
      id: '/api/public/claim-coupon'
      path: '/api/public/claim-coupon'
      fullPath: '/api/public/claim-coupon'
      preLoaderRoute: typeof ApiPublicClaimCouponRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EnvioRoute: EnvioRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RastreioRoute: RastreioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  TrocasRoute: TrocasRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  ApiPublicClaimCouponRoute: ApiPublicClaimCouponRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
